server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  pattern:
    console: "[%-5level] %d{HH:mm:ss} - %msg%n"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  token:
    secret: 1234566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expired: 3600000