server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  pattern:
    console: "[%-5level] %d{HH:mm:ss} - %msg%n"
jwt:
  token:
    secret: 1234566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expired: 3600000
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # SWAGGER DOC ROUTES
        - id: doc-auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}

        - id: doc-shop-service
          uri: lb://shop-service
          predicates:
            - Path=/shop/v3/api-docs
          filters:
            - RewritePath=/shop/(?<path>.*), /$\{path}

        - id: doc-user-service
          uri: lb://user-service
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

        # APPLICATION ROUTES

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/shop/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter

        - id: admin-service
          uri: lb://user-service
          predicates:
            - Path=/admin/**
          filters:
            - AuthenticationFilter
            - AdminFilter
springdoc:
  swagger-ui:
    urls:
      - name: auth
        url: /v3/api-docs/auth
      - name: shop
        url: /v3/api-docs/shop
      - name: user
        url: /v3/api-docs/user