version: '3.8'
services:
  config-service:
    image: shop/config-service:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8888
  discovery-service:
    image: shop/discovery-service:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      CONFIG_SERVER: http://config-service:8888/
  auth-service:
    image: shop/auth-service:latest
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      user-db:
        condition: service_started
    environment:
      CONFIG_SERVER: http://config-service:8888/
      EUREKA_SERVER: http://discovery-service:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db/auth
      SERVER_PORT: 8080
  user-service:
    image: shop/user-service:latest
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      auth-service:
        condition: service_started
      user-db:
        condition: service_started
    environment:
      CONFIG_SERVER: http://config-service:8888/
      EUREKA_SERVER: http://discovery-service:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db/auth
  user-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "15432:5432"
  shop-service:
    image: shop/shop-service:latest
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      shop-db:
        condition: service_started
    environment:
      CONFIG_SERVER: http://config-service:8888/
      EUREKA_SERVER: http://discovery-service:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://shop-db/shop
  shop-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "15433:5432"
  gateway:
    image: shop/gateway-service
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    environment:
      CONFIG_SERVER: http://config-service:8888/
      EUREKA_SERVER: http://discovery-service:8761/eureka/
    ports:
      - "8765:8765"

  front:
    image: shop/front-shop-service
    ports:
      - "4200:80"

