server:
  port: 8888
spring:
  profiles:
    include: native
  native:
    searchLocations: classpath:/config
  application:
    name: config-service
management:
  endpoints:
    web:
      exposure:
        include: "*"